### PR TITLE
Move homebrew scripts from the SDK repo to homebrew-dart

### PR DESCRIPTION
**Pull request by athomas**
@kevmoo FYI

### CODE REVIEW

**Comment by athomas** [comment]
@kevmoo @whesse @lrhn @keertip @sestegra

If you agree to your contributions being moved from the Dart SDK repo to this repo, please add a comment to this PR with the text `@googlebot I consent.`

**Comment by lrhn** [comment]
@googlebot I consent.

**Review by whesse — CHANGES_REQUESTED** [review]
Please add an AUTHORS and LICENSE file to this repo, since these files are being moved from a repo with these files.

Note that this commit copies the files from their previous location without changes, and follow-up commits will make necessary changes for them to work well in this new location.

**Comment by kevmoo** [comment]
Cool!

**Comment by msbit** [comment]
This is fine by me, but to be squeaky clean you may need sign off from @fsouza for my commit.

I'll hold of official consent for now, let me know how you want to proceed.

**Comment by fsouza** [comment]
@msbit you have my sign off. I assume I don't have to tell the bot, but let me know if I'm wrong :D

**Comment by msbit** [comment]
Thanks @fsouza!

So on behalf of both of us...

**Comment by msbit** [comment]
@googlebot I consent.

**Comment by athomas** [comment]
Given that the original authors gave their consent on the original Dart SDK CLs, I've overridden the googlebot's decision to block this.

**Review by whesse — APPROVED** [review]

**Pull request merged**
