### PR TITLE
Fixes dart-lang#58

### PR DESCRIPTION
**Pull request by itzsaga**
I think this one is pretty straightforward.

### CODE REVIEW

**Comment by Colbitron** [comment]
Beat me to the punch! For what it's worth, I can verify it works.

**Comment by itzsaga** [comment]
@Colbitron ha, yeah I saw this earlier after trying to run a `brew upgrade` and finally had a few minutes to spare to open the PR.

**Comment by kevmoo** [comment]
@whesse @athomas – I'm tempted to land this now to fix the existing issue. We'll need to make sure the next SDK roll we publish has these changes, too!

**Comment by kevmoo** [comment]
@whesse @athomas – I'm tempted to land this now to fix the existing issue. We'll need to make sure the next SDK roll we publish has these changes, too!

**Pull request merged**
