### PR TITLE
Use on_macos/on_linux in formulas

### PR DESCRIPTION
**Pull request by athomas**

### CODE REVIEW

**Comment by athomas** [comment]
The diff is much easier to look at if whitespace diffs are turned off.

**Comment by kevmoo** [comment]
ooo...that cleanup bot is nice.

Want to take a look at the lint suggestions before I dig in here?

**Comment by athomas** [comment]
Yes, I'll look at the other lints tomorrow. You can wait with taking a look.

**Comment by athomas** [comment]
Looks like those lints went away again 🤷

**Pull request closed without merging**
