### PR TITLE
Ability to install Dart 2.0.0 version

### PR DESCRIPTION
**Pull request by sinegovsky-ivan**

### CODE REVIEW

**Comment by sinegovsky-ivan** [comment]
I signed it!

**Comment by sinegovsky-ivan** [comment]
I signed it!

**Comment by sinegovsky-ivan** [comment]
I signed it!

**Comment by kevmoo** [comment]
We already have this here - https://github.com/dart-lang/homebrew-dart/blob/master/dart%402.rb

Right?

**Pull request closed without merging**
