### PR TITLE
Add support for Linux packages

### PR DESCRIPTION
**Pull request by eji**
This fixes enable to install the package via Linuxbrew. Could you please confirm it?

### CODE REVIEW

**Comment by eji** [comment]
@googlebot I signed it!

**Comment by kevmoo** [comment]
CC @whesse

**Comment by kevmoo** [comment]
We'll need to update the SDK script that generates this file.
@whesse has details

**Comment by eji** [comment]
https://github.com/dart-lang/homebrew-dart/issues/42#issuecomment-217215414

> We'll need to update the SDK script that generates this file.

@kevmoo I got it. Same PR ( https://github.com/dart-lang/sdk/pull/38512 ) was merged 6 days ago.

I'll close this PR.

Thanks!

**Comment by athomas** [comment]
Closing this based on https://github.com/dart-lang/homebrew-dart/pull/71#issuecomment-541491217.

**Comment by sestegra** [comment]
@eji I've read your PR, I forgot ARM architecture in previous PR (dart-lang/sdk#38512)
I've just created new PR to support ARM as well (dart-lang/sdk#38893)

**Pull request closed without merging**
