### PR TITLE
Fix dartium path to not include version in caveats

### LINKED ISSUE #32: brew location messages are inconsistent, confusing
When you install dartium using brew in the new world, you get a location in a different format from the Dart SDK location.

```
$ brew install dart --with-content-shell --with-dartium
...
Please note the path to the Dart SDK:
  <path-to-homebrew>/opt/dart/libexec

--with-dartium:
  To use with IntelliJ, set the Dartium execute home to:
    <path-to-homebrew>/Cellar/dart/1.10.1/Chromium.app
...
```
It'd look better and be easier to document if the Dartium location was instead the equivalent (as far as I can tell) `<path-to-homebrew/opt/dart/Chromium.app`.

Also, do we really want to mention IntelliJ by name, when WebStorm is what we've been recommending more? Perhaps:

```
The Dart SDK path (required by tools such as WebStorm) is:
  <path-to-homebrew>/opt/dart/libexec

--with-dartium:
The Dartium path (required by tools such as WebStorm) is:
  <path-to-homebrew>/opt/dart/Chromium.app
```

### PR DESCRIPTION
**Pull request by danthegoodman**
Fixes #32

### CODE REVIEW

**Comment by whesse** [comment]
The files in homebrew-dart are updated by a script in the Dart repository,
at tools/apps/update_homebrew/bin/update_homebrew.dart.  The cl needs to go
there, and we need a contributor agreement.  Or I can make the fix

**Comment by danthegoodman** [comment]
@whesse Sure thing! Can I also add a `contributing.md` which would inform other people to make the necessary changes there?

**Comment by danthegoodman** [comment]
Resubmitted through https://codereview.chromium.org/1211743002

**Comment by whesse** [comment]
Yes, that would be good, and can be put directly in the github repo.

On Thu, Jun 25, 2015 at 2:12 AM, Danny Kirchmeier <notifications@github.com>
wrote:

> @whesse <https://github.com/whesse> Sure thing! Can I also add a
> contributing.md which would inform other people to make the necessary
> changes there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/homebrew-dart/pull/34#issuecomment-115051552>
> .
>



-- 
William Hesse

**Pull request closed without merging**
