### PR TITLE
clarify where reviews take place

### PR DESCRIPTION
**Pull request by devoncarew**
- update the readme to clarify where reviews take place
- have dependabot assign owners (mostly for notification)
- have all PRs get the `review-using-gerrit` label

Feel free to update the PR as necessary (including removing the part about auto-assigning dependabot owners).

### CODE REVIEW

**Comment by sortie** [comment]
Thank you for your contribution. This project uses Gerrit for code reviews. Your
pull request has automatically been converted into a code review at:

None

Please wait for a developer to review your code review at the above link.
See CONTRIBUTING.md to learn how to upload changes to Gerrit directly. You can
speed up the review if you sign into Gerrit and manually add a reviewer that has
recently worked on the relevant code and they will help you. You can also push
additional commits to this pull request to update the code review.

**Comment by sortie** [comment]
https://dart-review.googlesource.com/c/homebrew-dart/+/280760 has been updated with the latest commits from this pull request.

**Comment by devoncarew** [comment]
OK, I've updated the PR to:

- add a contributing doc (our std one from the .github repo w/ updates for gerrit)
- update the readme
- remove the PR labelling stuff

The copybara 'Thank you for your contribution - here's a gerrit url' comments look great! I think they remove all the mystery around where to review and merge.

**Comment by devoncarew** [comment]
(triaging my PR queue)

**Pull request closed without merging**
