### PR TITLE
Fix undent warning

### LINKED ISSUE #48: Calling <<-EOS.undent is deprecated
Was told "Please report this to the dart-lang/dart tap!" so here i am .

```
➜  ~ brew info dart
dart-lang/dart/dart: stable 1.24.3, devel 2.0.0-dev.19.0
The Dart SDK
https://www.dartlang.org/
Not installed
From: https://github.com/dart-lang/homebrew-dart/blob/master/dart.rb
==> Options
--with-content-shell
	Download and install content_shell -- headless Dartium for testing
--with-dartium
	Download and install Dartium -- Chromium with Dart
--devel
	Install development version 2.0.0-dev.19.0
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/dart-lang/homebrew-dart/dart.rb:72:in `caveats'
Please report this to the dart-lang/dart tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/dart-lang/homebrew-dart/dart.rb:72:in `caveats'
Please report this to the dart-lang/dart tap!

==> Caveats
Please note the path to the Dart SDK:
  /usr/local/opt/dart/libexec

--with-dartium:
  To use with IntelliJ, set the Dartium execute home to:
    /usr/local/opt/dart/Chromium.app
```

### PR DESCRIPTION
**Pull request by fsouza**
Closes #48.

### CODE REVIEW

**Comment by kevmoo** [comment]
Thanks, @fsouza – we don't have tests for this. Have you verified this works?

**Comment by fsouza** [comment]
Hey @kevmoo, I have verified this with a simple uninstall + install of the ``dart`` formula. Is that enough?

**Comment by kevmoo** [comment]
> Hey @kevmoo, I have verified this with a simple uninstall + install of the dart formula. Is that enough?

SGTM. @whesse ?

**Comment by whesse** [comment]
Edited my previous, mistaken LGTM.  I'll close this PR, since a new one on dart-lang/sdk needs to be started.  We should add to the README for this repo, indicating that the dart.rb file is generated by a script, and cannot be modified manually.

**Comment by whesse** [comment]
The idea for the fix is correct, but the change cannot be made in this repo. The dart.rb file is automatically generated by an app in the Dart SDK repo, in tools/apps/update_homebrew.

The file tools/apps/update_homebrew/lib/update_homebrew.dart needs to be modified to use the ~ instead of .undent on the EOS here delimiter.

**Pull request closed without merging**
